openapi: '3.0.1'
info:
  title: Riot Global Rankings
  version: 1.0.1
servers:
  - url: https://jl6pbvlttd.execute-api.us-east-1.amazonaws.com/Prod
paths:
  /tournament_rankings/{tournament_id}:
    get:
      tags:
        - Tournament Rankings
      summary: Get Tournament Rankings
      parameters:
        - name: tournament_id
          in: path
          description: ID of tournament to return rankings for
          required: true
          schema:
            type: string
          default: '110825936250664572'
        - name: stage
          in: query
          description: Stage of tournament to return rankings for
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TeamResponse'
            application/json:
              example:
                TeamID: '123'
                TeamCode: TEAM1
                TeamName: Team 1
                Rank: 1
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
            application/json:
              example:
                error: invalid tournament id path parameter
  /global_rankings:
    get:
      tags:
        - Global Rankings
      summary: Get Global Rankings
      parameters:
        - name: number_of_teams
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamResponse'
            application/json:
              example:
                - TeamID: '123'
                  TeamCode: TEAM1
                  TeamName: Team 1
                  Rank: 1
                - TeamID: '124'
                  TeamCode: TEAM2
                  TeamName: Team 2
                  Rank: 2
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
            application/json:
              example:
                error: HTTP METHOD not supported
  /team_rankings:
    get:
      tags:
        - Team Rankings
      summary: Get Team Rankings
      parameters:
        - name: team_ids
          in: query
          description: IDs of tournaments to return ranking for
          required: true
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
          default: 100205573495116443,104710343016706538,108159996371573462
      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamResponse'
            application/json:
              example:
                - TeamID: '123'
                  TeamCode: TEAM1
                  TeamName: Team 1
                  Rank: 1
                - TeamID: '124'
                  TeamCode: TEAM2
                  TeamName: Team 2
                  Rank: 2
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiError'
            application/json:
              example:
                error: >-
                  invalid team_ids query parameter expected list of ids
                  seperated by ','
components:
  schemas:
    ApiError:
      type: object
      properties:
        error:
          type: string
    TeamResponse:
      type: object
      properties:
        TeamID:
          type: string
        TeamCode:
          type: string
        TeamName:
          type: string
        Rank:
          type: integer
        TotalWins:
          type: integer
        TotalLosses:
          type: integer
        TotalTies:
          type: integer